### PR TITLE
Provider fixes

### PR DESCRIPTION
**Pull request by mnlipp**
Fixes the explicitly specified OSGi headers as explained for angus activation [here](https://github.com/eclipse-ee4j/angus-activation/issues/35).

### CODE REVIEW

**Review by lukasj — CHANGES_REQUESTED** [review]
drop the first commit from this PR so it applies cleanly

**Comment by mnlipp** [comment]
> drop the first commit from this PR so it applies cleanly

I cannot provide a PR against master (at least not a tested one) because master currently doesn't build (`maven package` fails). So this is actually a diff against 2.0.1.

**Comment by mnlipp** [comment]
Works. I've tested it with the angus-activation (as of https://github.com/eclipse-ee4j/angus-activation/pull/37), jakarta.activation-api:2.1.1 and jakarta.mail-api:2.1.1. No more hk2 service loader needed!

Sorry about this not being mergeable. `mvn package` works with master today (no idea why it didn't yesterday) and so I rebased the branch on master. But for some reason maven changes the version in pom.xml when building. (I'll never understand maven and luckily I don't have to.)

**Comment by lukasj** [comment]
You should be able to rebase now to get rid of the first commit, I believe the problem you had is fixed by #89 (workaround would be to use `mvn -Poss-release -Dgpg.skip=true ...`).

One more change to do is to put a note into [changes.txt](https://github.com/eclipse-ee4j/angus-mail/blob/master/doc/src/main/resources/docs/CHANGES.txt#L14) and we're done here

**Review by lukasj — APPROVED** [review]

**Comment by lukasj** [comment]
thank you!

**Pull request merged**
