### PR TITLE
Remove SecurityManager references from logging package #16

### PR DESCRIPTION
**Pull request by jmehrens**
Signed-off-by: jmehrens <jason_mehrens@hotmail.com>

### CODE REVIEW

**Comment by jmehrens** [comment]
Summary of changes:
1. Removed the security manager test to verify methods throw when under the security manager and logging control is not granted.  The only way to bring this test back is to create a test to run with custom log manager that can replace the global logger with a custom class.  I don't think this is worth doing.
2. Removed 2 tests related to verifying a memory optimization around super error manager.  This test doesn't really have anything to do with correctness so the loss of coverage is not a big deal.
3. Some of the existing SecurityManager test around the context class loader were updated to use a custom thread instead of a SecurityManager.
4. New method and tests were added to optionally invoke the AccessController if is still present.  This only happens if permissions fail when attempting an operation without privileges.

**Comment by jmehrens** [comment]
Summary of build using /usr/lib/jvm/jdk-21-oracle-x64 to show that changes work:
------------------------------------------------------------------------
Reactor Summary for Angus Mail Project 2.0.3-SNAPSHOT:

Angus Mail Project ................................. SUCCESS [ 45.369 s]
Angus Mail Core .................................... SUCCESS [ 27.830 s]
Angus Mail providers ............................... SUCCESS [  0.114 s]
Angus Mail imap provider ........................... SUCCESS [  7.682 s]
Angus Mail smtp provider ........................... SUCCESS [  2.039 s]
Angus Mail pop3 provider ........................... SUCCESS [  1.724 s]
Angus Mail logging handler ......................... SUCCESS [  3.471 s]
Angus Mail Provider ................................ SUCCESS [04:15 min]
Angus Mail default provider ........................ SUCCESS [ 14.756 s]
Angus Mail dsn support ............................. SUCCESS [  2.307 s]
Angus Mail Gmail IMAP provider ..................... SUCCESS [  2.015 s]
Angus Mail mbox provider ........................... SUCCESS [ 33.610 s]
Jakarta Mail API demos ............................. SUCCESS [  0.097 s]
Jakarta Mail API demo .............................. SUCCESS [  3.050 s]
Jakarta Mail API demo client ....................... SUCCESS [  1.169 s]
Jakarta Mail API demo servlet ...................... SUCCESS [  2.496 s]
Jakarta Mail API demo taglib ....................... SUCCESS [  2.627 s]
Jakarta Mail API demo webapp ....................... SUCCESS [  1.548 s]
Jakarta Mail API logging demo ...................... SUCCESS [  4.679 s]
Jakarta Mail API demo Outlook message support ...... SUCCESS [  0.550 s]
Angus Mail documentation ........................... SUCCESS [ 19.608 s]
------------------------------------------------------------------------
BUILD SUCCESS
------------------------------------------------------------------------
Total time:  07:13 min

**Review by lukasj — COMMENTED** [review]
* MailHandler is missing  cp year update
* I prefer `Objects.requireNonNull` over `if (x == null) throw new NPE` (in LogManagerProperties) but that is a matter of taste

**Comment by jmehrens** [comment]
@lukasj 
> * MailHandler is missing  cp year update
> 
>     * I prefer `Objects.requireNonNull` over `if (x == null) throw new NPE` (in LogManagerProperties) but that is a matter of taste

Fixed copywrite year.  I updated the code to use requireNonNull.  There is one case that is omitted because the argument is a Throwable which interestingly enough will trigger an IDE warning that return type of Throwable was not read.  That method will be dealt with in a follow on ticket.

**Review by lukasj — APPROVED** [review]

**Comment by lukasj** [comment]
thanks!

**Pull request merged**
